### ISSUE TITLE
Doesn't appear to be doing anything

### ISSUE THREAD

**Issue by recurrence** [duyvhh/jenkins-sms#1]
Doesn't send an SMS and there's no errors in either the job or system logs.  It just doesn't seem to work.

Does anyone see this running in their instance?

**Comment by duyvhh** [comment]
@recurrence I'm using this plugin and it's working fine. Make sure that you have some credits in your Hoiio Developer Account. See this screenshot: http://i.imgur.com/C33ssFL.png

If you are trying out, let me know your developer account info (the registered number will do) and I'll add some trial credits to your account.

**Comment by recurrence** [comment]
Hi @stvvan 

Thanks, I do have $10 on there.  I'll see if something else might be wrong.

Are you using a recent Jenkins build?

**Comment by duyvhh** [comment]
@recurrence I'm using 1.632 at the moment. Not sure if 1.633 breaks anything.

Anyway, have you tried calling the API directly with the given credentials yet?

**Comment by recurrence** [comment]
Hi stvvan, I checked out the project and am loading it up as a local jenkins plugin to debug.  thanks!

Good to know it's working for someone, hence it is highly likely an error on my side somewhere.

Going to close this unless I see a legitimate problem, I'll send a PR then
